import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, Database, Eye, LoaderCircle, RotateCcw, Search, Server, X } from 'lucide-react';
import { MappingObjectType } from '../stage1MappingTypes';
import { ExecutionSchedule, scheduleLabel } from '../data/operations';
import { TargetSyncRecord, TargetSyncStatus, initialTargetSyncRecords, targetSyncStatusLabel } from '../data/targetSyncRecords';

const rootName: Record<string, string> = { PART: '零部件', DOCUMENT: '文档', PROCESS: '工艺路线' };
const statusClass: Record<TargetSyncStatus, string> = {
  PENDING: 'bg-[var(--ty-fill-weak-dark-color)] text-[var(--ty-font-sub-color)] border-[var(--ty-border-color)]',
  PROCESSING: 'bg-[var(--ty-primary-lightest-color)] text-[var(--ty-primary-color)] border-[var(--ty-primary-color)]/30',
  SUCCESS: 'bg-[var(--ty-green-lightest-color)] text-[var(--ty-green-color)] border-[var(--ty-green-color)]/30',
  FAILED: 'bg-[var(--ty-red-lightest-color)] text-[var(--ty-red-color)] border-[var(--ty-red-color)]/30',
};

export function ManticoreSyncQueueView({ roots, schedules, records = initialTargetSyncRecords, initialRootTypeFilter = 'ALL' }: { roots: MappingObjectType[]; schedules: ExecutionSchedule[]; records?: TargetSyncRecord[]; initialRootTypeFilter?: string }) {
  const [rootType, setRootType] = useState(initialRootTypeFilter);
  const [status, setStatus] = useState<'ALL' | TargetSyncStatus>('ALL');
  const [keyword, setKeyword] = useState('');
  const [detailId, setDetailId] = useState<string | null>(null);
  const scoped = useMemo(() => records.filter((row) => rootType === 'ALL' || row.rootTypeCode === rootType), [records, rootType]);
  const visible = useMemo(() => scoped.filter((row) => {
    if (status !== 'ALL' && row.status !== status) return false;
    const term = keyword.trim().toLowerCase();
    return !term || [row.id, row.objectId, row.stagingTable, row.targetIndex, row.errorCode, row.errorSummary, row.traceId].some((value) => value?.toLowerCase().includes(term));
  }), [scoped, status, keyword]);
  const detail = records.find((row) => row.id === detailId);
  const count = (target: TargetSyncStatus) => scoped.filter((row) => row.status === target).length;
  const selectedRoot = roots.find((root) => root.id === rootType);
  const activeRoots = roots.filter((root) => root.accessEnabled).length;
  useEffect(() => { if (!detailId) return; const close = (event: KeyboardEvent) => event.key === 'Escape' && setDetailId(null); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [detailId]);

  return <div className="min-w-0 space-y-4">
    <header className="bg-[var(--ty-fill-white-color)] border border-[var(--ty-border-color)] rounded-ty-sm px-4 py-3 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Database className="w-5 h-5 text-[var(--ty-primary-color)]" /><div><div className="flex items-center gap-2"><h1 className="text-ty-xl font-semibold">Manticore 同步队列</h1><span className="text-ty-2xs min-h-6 px-2 inline-flex items-center rounded-ty-xs bg-[var(--ty-fill-color)] text-[var(--ty-font-sub-color)] border border-[var(--ty-border-color)]">中间表 → Manticore</span></div><p className="mt-1 text-ty-xs text-[var(--ty-font-sub-color)]">常驻服务按对象类型轮询中间表，发现新记录后逐条写入目标索引。</p></div></div><div className="flex items-center gap-2 text-ty-xs"><span className="min-h-6 px-2 inline-flex items-center rounded-ty-xs bg-[var(--ty-green-lightest-color)] text-[var(--ty-green-color)] border border-[var(--ty-green-color)]/30"><Server className="w-3.5 h-3.5 mr-1" />同步服务运行中</span><span className="text-[var(--ty-font-sub-color)]">已启用 {activeRoots} / {roots.length} 个类型</span></div></header>

    <section className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-3">{[
      ['待处理', count('PENDING'), <Clock3 className="w-4 h-4" />], ['处理中', count('PROCESSING'), <LoaderCircle className="w-4 h-4" />], ['已处理', count('SUCCESS') + count('FAILED'), <Database className="w-4 h-4" />], ['同步成功', count('SUCCESS'), <CheckCircle2 className="w-4 h-4" />], ['同步失败', count('FAILED'), <AlertTriangle className="w-4 h-4" />],
    ].map(([label, value, icon]) => <div key={String(label)} className="bg-white border border-[var(--ty-border-color)] rounded-ty-sm p-4 flex items-center justify-between"><div><span className="text-ty-xs text-[var(--ty-font-sub-color)] block">{label}</span><strong className="text-ty-xl mt-0.5 block font-mono">{value}</strong></div><div className="w-9 h-9 rounded-ty-sm bg-[var(--ty-fill-color)] text-[var(--ty-font-sub-color)] flex items-center justify-center">{icon}</div></div>)}</section>

    <section className="bg-white border border-[var(--ty-border-color)] rounded-ty-sm p-3 flex flex-wrap items-end gap-3"><label className="text-ty-xs text-[var(--ty-font-sub-color)] space-y-1"><span className="block">对象类型</span><select value={rootType} onChange={(e) => setRootType(e.target.value)} aria-label="同步队列对象类型" className="h-8 min-w-36 px-3 border border-[var(--ty-border-color)] rounded-ty-sm bg-white"><option value="ALL">全部类型</option>{roots.map((root) => <option key={root.id} value={root.id}>{rootName[root.id]}</option>)}</select></label><label className="text-ty-xs text-[var(--ty-font-sub-color)] space-y-1"><span className="block">消息状态</span><select value={status} onChange={(e) => setStatus(e.target.value as 'ALL' | TargetSyncStatus)} aria-label="同步队列状态" className="h-8 min-w-36 px-3 border border-[var(--ty-border-color)] rounded-ty-sm bg-white"><option value="ALL">全部状态</option>{Object.entries(targetSyncStatusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-ty-xs text-[var(--ty-font-sub-color)] space-y-1 flex-1 min-w-56"><span className="block">消息 / 对象 / 异常</span><span className="relative block"><Search className="w-3.5 h-3.5 absolute left-2.5 top-2.5" /><input aria-label="搜索同步队列" value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="输入关键字" className="h-8 w-full pl-8 pr-2 border border-[var(--ty-border-color)] rounded-ty-sm" /></span></label><button type="button" onClick={() => { setRootType('ALL'); setStatus('ALL'); setKeyword(''); }} className="h-8 px-3 border border-[var(--ty-border-color)] rounded-ty-sm text-ty-xs flex items-center gap-2 hover:bg-[var(--ty-fill-weak-dark-color)]"><RotateCcw className="w-3.5 h-3.5" />重置</button></section>

    <div className="bg-[var(--ty-primary-lightest-color)]/35 border border-[var(--ty-primary-color)]/20 rounded-ty-sm px-3 py-2 text-ty-xs flex flex-wrap items-center justify-between gap-2"><span>{selectedRoot ? `${rootName[selectedRoot.id]}：${selectedRoot.accessEnabled ? scheduleLabel(schedules.find((item) => item.rootTypeCode === selectedRoot.id), selectedRoot.pollingIntervalMinutes) : '已停用，不轮询'}` : '各对象类型按独立检查频率轮询，队列按单条对象处理。'}</span><span className="text-[var(--ty-font-sub-color)]">积压量 = 待处理 + 处理中</span></div>

    <section className="bg-white border border-[var(--ty-border-color)] rounded-ty-sm overflow-hidden"><div className="px-4 py-3 border-b border-[var(--ty-border-color)]"><h2 className="text-ty-sm font-semibold">消息明细</h2><p className="text-ty-xs text-[var(--ty-font-sub-color)] mt-1">共 {visible.length} 条；每条中间表记录对应一条消费结果。</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-ty-xs"><thead className="bg-[var(--ty-fill-weak-dark-color)] text-[var(--ty-font-sub-color)]"><tr><th className="px-3 py-2 text-left">消息 / 发现时间</th><th className="px-3 py-2 text-left">对象 / 类型</th><th className="px-3 py-2 text-left">同步链路</th><th className="px-3 py-2 text-left">状态</th><th className="px-3 py-2 text-left">完成时间</th><th className="px-3 py-2 text-left">结果摘要</th><th className="px-3 py-2 text-center">操作</th></tr></thead><tbody className="divide-y divide-[var(--ty-border-light-color)]">{visible.map((row) => <tr key={row.id} className="hover:bg-[var(--ty-fill-weak-dark-color)]/50"><td className="px-3 py-2"><strong className="font-mono">{row.id}</strong><span className="block text-[var(--ty-font-sub-color)] mt-1">{row.detectedAt}</span></td><td className="px-3 py-2"><strong>{row.objectId}</strong><span className="block text-[var(--ty-font-sub-color)] mt-1">{rootName[row.rootTypeCode]}</span></td><td className="px-3 py-2"><span>{row.stagingTable}</span><span className="block text-[var(--ty-font-sub-color)] mt-1">→ {row.targetIndex}</span></td><td className="px-3 py-2"><span className={`min-h-6 px-2 inline-flex items-center rounded-ty-xs border font-medium ${statusClass[row.status]}`}>{row.status === 'PROCESSING' && <LoaderCircle className="w-3 h-3 mr-1 animate-spin" />}{targetSyncStatusLabel[row.status]}</span></td><td className="px-3 py-2 font-mono text-[var(--ty-font-sub-color)]">{row.processedAt || '—'}</td><td className="px-3 py-2"><span className={row.status === 'FAILED' ? 'text-[var(--ty-red-color)]' : 'text-[var(--ty-font-sub-color)]'}>{row.errorSummary || (row.status === 'SUCCESS' ? '已写入目标索引' : row.status === 'PROCESSING' ? '正在写入目标索引' : '等待同步服务消费')}</span></td><td className="px-3 py-2 text-center"><button type="button" onClick={() => setDetailId(row.id)} className="h-8 px-2 text-[var(--ty-primary-color)] inline-flex items-center gap-1 hover:underline"><Eye className="w-3.5 h-3.5" />详情</button></td></tr>)}</tbody></table></div>{!visible.length && <div className="p-10 text-center text-ty-xs text-[var(--ty-font-sub-color)]">当前条件下暂无消息</div>}</section>

    {detail && <div className="fixed inset-0 z-50 bg-ty-overlay flex items-center justify-center p-4" onMouseDown={(e) => e.target === e.currentTarget && setDetailId(null)}><section role="dialog" aria-modal="true" aria-label="同步消息详情" className="w-[min(640px,calc(100vw-32px))] bg-white border border-[var(--ty-border-color)] rounded-ty-lg shadow-ty-lg overflow-hidden"><header className="px-4 py-3 bg-[var(--ty-fill-weak-dark-color)] border-b flex justify-between items-center"><div><h2 className="text-ty-lg font-semibold">{detail.objectId} · 同步详情</h2><p className="text-ty-xs text-[var(--ty-font-sub-color)] mt-1 font-mono">{detail.id}</p></div><button aria-label="关闭详情" onClick={() => setDetailId(null)} className="w-8 h-8 flex items-center justify-center rounded-ty-sm hover:bg-[var(--ty-fill-color)]"><X className="w-4 h-4" /></button></header><div className="p-4 grid grid-cols-2 gap-4 text-ty-xs"><div><span className="text-[var(--ty-font-sub-color)] block">对象类型</span><strong>{rootName[detail.rootTypeCode]}</strong></div><div><span className="text-[var(--ty-font-sub-color)] block">状态</span><strong>{targetSyncStatusLabel[detail.status]}</strong></div><div><span className="text-[var(--ty-font-sub-color)] block">中间表</span><strong>{detail.stagingTable}</strong></div><div><span className="text-[var(--ty-font-sub-color)] block">目标索引</span><strong>{detail.targetIndex}</strong></div><div><span className="text-[var(--ty-font-sub-color)] block">发现时间</span><strong className="font-mono">{detail.detectedAt}</strong></div><div><span className="text-[var(--ty-font-sub-color)] block">处理次数</span><strong>{detail.attempt}</strong></div><div className="col-span-2"><span className="text-[var(--ty-font-sub-color)] block">追踪编号</span><strong className="font-mono">{detail.traceId}</strong></div>{detail.errorSummary && <div className="col-span-2 p-3 rounded-ty-sm bg-[var(--ty-red-lightest-color)] border border-[var(--ty-red-color)]/30"><strong className="text-[var(--ty-red-color)]">{detail.errorCode}</strong><p className="mt-1">{detail.errorSummary}</p></div>}</div><footer className="px-4 py-3 bg-[var(--ty-fill-weak-dark-color)] border-t flex justify-end"><button className="h-8 px-4 border border-[var(--ty-border-color)] rounded-ty-sm bg-white" onClick={() => setDetailId(null)}>关闭</button></footer></section></div>}
  </div>;
}
